export const AUTH_GRANT = 'AUTH_GRANT'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_EXPIRED = 'AUTH_EXPIRED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_REVOKE = 'AUTH_REVOKE'
